"""followers

Revision ID: 003e57ffaf9f
Revises: d456c63e9007
Create Date: 2020-04-11 19:47:07.401702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003e57ffaf9f'
down_revision = 'd456c63e9007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
